# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise32"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  # Custom args for virtualbox
  config.vm.provider "virtualbox" do |v|
    # Limit CPU usage to 50%
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
    # Give the VM 3G of RAM
    v.customize ["modifyvm", :id, "--memory", "3072"]
  end

  # Port forwarding for Weblogic
  config.vm.network :forwarded_port, guest: 7001, host: 7001

  # Use the bootstrap.sh to bootstrap this image
  config.vm.provision :shell, :path => "bootstrap.sh"
end
