# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.

  # Official Ubuntu 13.04 Cloud image found at http://www.vagrantbox.es/
  config.vm.box = "raring-server-cloudimg-i386-vagrant"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-i386-vagrant-disk1.box"

  # Custom args for virtualbox
  config.vm.provider "virtualbox" do |v|
    # Limit CPU usage to 80%
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
    # Give the VM 3G of RAM
    v.customize ["modifyvm", :id, "--memory", "3072"]
  end

  # Port forwarding for Graphite
  config.vm.network :forwarded_port, guest: 80, host: 8787
  config.vm.network :forwarded_port, guest: 2003, host: 2003
  config.vm.network :forwarded_port, guest: 2004, host: 2004

  # Use the bootstrap.sh to bootstrap this image
  config.vm.provision :shell, :path => "bootstrap.sh"
end
